// СГЕНЕРИРОВАНО. Не править руками.
//
// Адреса справочника terrytrilla.com, по которым термин в посте можно сделать
// ссылкой. ⚠️ Ссылаемся ТОЛЬКО по этому списку: проверка живьём показала, что
// /chords/dm7 существует, а /chords/m7 отвечает 404 — ссылка наугад водила бы
// людей в пустоту. Нет в списке — термин оформляется, но ссылкой не становится.
//
// Источник: apps/web/src/content/catalog/{chords,root-chords,scales,root-scales}/en.json

export const CHORDS = new Set(["a","a6","a7","a9","add11","add2","add9","addSharp11","adim","alteredFull","am","am6","am7","amaj7","asus2","asus4","augmented","augmented7","augmentedMajor7","b","b6","b7","b9","bb","bb6","bb7","bb9","bbm","bbmaj7","bdim","bm","bm7","bmaj7","bsus4","c","c6","c7","c9","cdim","cm","cm6","cm7","cmaj7","csus2","csus4","d","d6","d7","d9","daug","diminished","diminished7","diminishedMajor7","dm","dm6","dm7","dmaj7","dominant11","dominant13","dominant13b9","dominant13sharp11","dominant13sharp9","dominant13sus4","dominant7","dominant7flat13","dominant7flat5","dominant7flat5flat9","dominant7flat5sharp9","dominant7flat9","dominant7no5","dominant7sharp11","dominant7sharp5flat9","dominant7sharp5sharp9","dominant7sharp9","dominant7sus2","dominant7sus4","dominant9","dominant9b5","dominant9sharp11","dominant9sharp5","dominant9sus4","dsus2","dsus4","e","e6","e7","e9","edim","em","em6","em7","emaj7","esus4","f","f6","f7","f9","fm","fm6","fm7","fmaj7","fsus2","g","g6","g7","g9","gaug","gdim","gm","gm6","gm7","gmaj7","gsus2","gsus4","halfDiminished7","major","major11","major13","major6","major7","major7flat5","major7sharp11","major7sus2","major7sus4","major9","major9sharp11","minor","minor11","minor13","minor6","minor7","minor7sharp5","minor9","minor9b5","minorAdd11","minorAdd2","minorAdd9","minorMajor7","minorMajor9","minorSixNine","power","powerInverted","powerOctave","quartal3","quartal4","quintal3","quintal4","sixNine","so_what","sus2","sus24","sus4","susFlat9"]);

export const SCALES = new Set(["a-blues","a-dorian","a-lydian","a-major","a-minor","a-mixolydian","a-phrygian","aeolian","aeolianSharp4","alteredDiminished","alteredDiminishedBb3","alteredDominantBb3","alteredDominantNat2","alteredScale","augmented","b-blues","b-dorian","b-major","b-minor","b-mixolydian","b-phrygian","bb-blues","bb-dorian","bb-major","bb-minor","bb-mixolydian","bebopDominant","bebopDorian","bebopMajor","bebopMinor","blues","bluesMajor","bluesMinor","c-blues","c-dorian","c-lydian","c-major","c-minor","c-mixolydian","c-phrygian","chromatic","d-blues","d-dorian","d-lydian","d-major","d-minor","d-mixolydian","d-phrygian","diminishedHW","diminishedWH","dorian","dorianB2","dorianB5","dorianSharp4","doubleHarmonicMajor","e-blues","e-dorian","e-lydian","e-major","e-minor","e-mixolydian","e-phrygian","egyptian","f-blues","f-dorian","f-lydian","f-major","f-minor","f-mixolydian","g-blues","g-dorian","g-lydian","g-major","g-minor","g-mixolydian","g-phrygian","harmonicMajor","harmonicMinor","hirajoshi","hungarianMinor","inSen","ionian","ionianAugmentedSharp2","ionianSharp2","ionianSharp5","iwato","kumoi","locrian","locrianBb3Bb7","locrianBb7","locrianDominant","locrianNat2","locrianNat6","lydian","lydianAugmented","lydianAugmentedDominant","lydianAugmentedSharp2","lydianAugmentedSharp6","lydianB3","lydianDominant","lydianDominantB6","lydianSharp2","lydianSharp2Sharp6","lydianSharp6","majorBlues","majorLocrian","majorPentatonic","melodicMinor","minorPentatonic","mixolydian","mixolydianAugmented","mixolydianB2","mixolydianB6","neapolitanMajor","neapolitanMinor","oriental","phrygian","phrygianB4","phrygianDominant","prometheus","tritone","twoSemitoneTritone","ultraphrygian","wholeTone","yo"]);
